/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Timetable.Management.System;

import static Timetable.Management.System.RoomForConsSession.DB_URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LENOVO
 */
public class LecturerStatistics extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:mysql://localhost:3306/timetablems";
    static final String username = "root";
    static final String password = "1234";
    /**
     * Creates new form LecturerStatistics
     */
    public LecturerStatistics() {
        initComponents();
        showDetails();
    }

    private Connection DoConnect(){
        Connection conn=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");   
            conn = DriverManager.getConnection(DB_URL, username, password);
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(LecturerStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(LecturerStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }          
        return conn;
    }
    
    private void showDetails(){
        
        // get statistic results
        Connection conn = DoConnect();
        try { 
            ResultSet totalLectureCount = conn.createStatement().executeQuery("SELECT count(DISTINCT id) FROM lecturer");  // lecturer count
            ResultSet totalProfCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '1-Professor' "); // professor
            ResultSet totalAssProfCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '2-Assisstant Professor' "); // assisstant professor
            ResultSet totalHGCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '3-Senior Lecturer(HG)' "); // HG
            ResultSet totalSenLecCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '4-Senior Lecturer' "); // Senior Lec
            ResultSet totalLecCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '5-Lecturer' "); // Lecturer
            ResultSet totalAssLecCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '6-Assisstant Lecturer' "); // Lecturer
            ResultSet totalInsCount = conn.createStatement().executeQuery("SELECT count(id) FROM lecturer WHERE level = '7-Instructors' "); //instructors
            
            
            while(totalLectureCount.next()){
                String result = totalLectureCount.getString(1);
                JLabel_totalLectureCount.setText(result);
            }
            while(totalProfCount.next()){
                String result = totalProfCount.getString(1);
                JLabel_numberOfProfessors.setText(result);
            }
            while(totalAssProfCount.next()){
                String result = totalAssProfCount.getString(1);
                JLabel_numberOfAssisstantProfs.setText(result);
            }
            while(totalHGCount.next()){
                String result = totalHGCount.getString(1);
                JLabel_numberOfHGLecs.setText(result);
            }
            while(totalSenLecCount.next()){
                String result = totalSenLecCount.getString(1);
                JLabel_numberOfSenLecs.setText(result);
            }
            while(totalLecCount.next()){
                String result = totalLecCount.getString(1);
                JLabel_numberOfLecs.setText(result);
            }
            while(totalAssLecCount.next()){
                String result = totalAssLecCount.getString(1);
                JLabel_numberOfAssistantLecs.setText(result);
            }
            while(totalInsCount.next()){
                String result = totalInsCount.getString(1);
                JLabel_numberOfIns.setText(result);
            }
    
        }catch(SQLException ex){
            Logger.getLogger(LecturerStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JLabel_totalLectureCount = new javax.swing.JLabel();
        JLabel_numberOfProfessors = new javax.swing.JLabel();
        JLabel_numberOfAssisstantProfs = new javax.swing.JLabel();
        JLabel_numberOfHGLecs = new javax.swing.JLabel();
        JLabel_numberOfSenLecs = new javax.swing.JLabel();
        JLabel_numberOfLecs = new javax.swing.JLabel();
        JLabel_numberOfAssistantLecs = new javax.swing.JLabel();
        JLabel_numberOfIns = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lecturerStatistics.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemStatisticsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Number of Lecturers : ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Number of Professors : ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Number of  Assisstant Professors : ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Number of Senior Lecturers (HG) : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Number of Senior Lecturers : ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Number of Lecturers : ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Number of Assisstant Lecturers : ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Number of Instructors : ");

        JLabel_totalLectureCount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_totalLectureCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_totalLectureCount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfProfessors.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfProfessors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfProfessors.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfAssisstantProfs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfAssisstantProfs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfAssisstantProfs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfHGLecs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfHGLecs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfHGLecs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfSenLecs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfSenLecs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfSenLecs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfLecs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfLecs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfLecs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfAssistantLecs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfAssistantLecs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfAssistantLecs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel_numberOfIns.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_numberOfIns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_numberOfIns.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabel_totalLectureCount, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfProfessors))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfAssisstantProfs))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfHGLecs))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfSenLecs))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfLecs))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfAssistantLecs))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabel_numberOfIns))))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JLabel_numberOfAssisstantProfs, JLabel_numberOfAssistantLecs, JLabel_numberOfHGLecs, JLabel_numberOfIns, JLabel_numberOfLecs, JLabel_numberOfProfessors, JLabel_numberOfSenLecs, JLabel_totalLectureCount});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_totalLectureCount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfProfessors))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfAssisstantProfs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfHGLecs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfSenLecs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfLecs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfAssistantLecs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_numberOfIns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JLabel_numberOfAssisstantProfs, JLabel_numberOfAssistantLecs, JLabel_numberOfHGLecs, JLabel_numberOfIns, JLabel_numberOfLecs, JLabel_numberOfProfessors, JLabel_numberOfSenLecs, JLabel_totalLectureCount});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SystemStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemStatisticsActionPerformed
        // TODO add your handling code here:
        new SystemStatistics().setVisible(true);
        dispose();
    }//GEN-LAST:event_SystemStatisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_numberOfAssisstantProfs;
    private javax.swing.JLabel JLabel_numberOfAssistantLecs;
    private javax.swing.JLabel JLabel_numberOfHGLecs;
    private javax.swing.JLabel JLabel_numberOfIns;
    private javax.swing.JLabel JLabel_numberOfLecs;
    private javax.swing.JLabel JLabel_numberOfProfessors;
    private javax.swing.JLabel JLabel_numberOfSenLecs;
    private javax.swing.JLabel JLabel_totalLectureCount;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
