/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Timetable.Management.System;

/**
 *
 * @author swpas
 */
public class SystemDashboard extends javax.swing.JFrame {

    /**
     * Creates new form SystemDashboard
     */
    public SystemDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SystemLecturer = new javax.swing.JButton();
        SystemSubject = new javax.swing.JButton();
        SystemTag = new javax.swing.JButton();
        SystemLocation = new javax.swing.JButton();
        SystemWorkDays = new javax.swing.JButton();
        SystemTimeTable = new javax.swing.JButton();
        SystemStatistic = new javax.swing.JButton();
        SystemStudent = new javax.swing.JButton();
        SystemSession = new javax.swing.JButton();
        SystemSessionOther = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Table Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 750));
        setMinimumSize(new java.awt.Dimension(1400, 750));
        setName("SystemDashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1400, 750));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Time Table Management System");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgroung3.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        SystemLecturer.setBackground(new java.awt.Color(204, 204, 204));
        SystemLecturer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemLecturer.setText("Lecturers");
        SystemLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemLecturerActionPerformed(evt);
            }
        });

        SystemSubject.setBackground(new java.awt.Color(204, 204, 204));
        SystemSubject.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemSubject.setText("Subject");
        SystemSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemSubjectActionPerformed(evt);
            }
        });

        SystemTag.setBackground(new java.awt.Color(204, 204, 204));
        SystemTag.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemTag.setText("Tags");
        SystemTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemTagActionPerformed(evt);
            }
        });

        SystemLocation.setBackground(new java.awt.Color(204, 204, 204));
        SystemLocation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemLocation.setText("Location");
        SystemLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemLocationActionPerformed(evt);
            }
        });

        SystemWorkDays.setBackground(new java.awt.Color(204, 204, 204));
        SystemWorkDays.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemWorkDays.setText("Working Days & Hours");
        SystemWorkDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemWorkDaysActionPerformed(evt);
            }
        });

        SystemTimeTable.setBackground(new java.awt.Color(204, 204, 204));
        SystemTimeTable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemTimeTable.setText("Time Table");
        SystemTimeTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemTimeTableActionPerformed(evt);
            }
        });

        SystemStatistic.setBackground(new java.awt.Color(204, 204, 204));
        SystemStatistic.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemStatistic.setText("Statistic");
        SystemStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemStatisticActionPerformed(evt);
            }
        });

        SystemStudent.setBackground(new java.awt.Color(204, 204, 204));
        SystemStudent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemStudent.setText("Student");
        SystemStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemStudentActionPerformed(evt);
            }
        });

        SystemSession.setBackground(new java.awt.Color(204, 204, 204));
        SystemSession.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemSession.setText("Session");
        SystemSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemSessionActionPerformed(evt);
            }
        });

        SystemSessionOther.setBackground(new java.awt.Color(204, 204, 204));
        SystemSessionOther.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemSessionOther.setText("Other Session");
        SystemSessionOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemSessionOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SystemSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SystemStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SystemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SystemTag, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SystemWorkDays, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SystemStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SystemSessionOther, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SystemTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SystemSession, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SystemLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemSession, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SystemSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemTag, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemWorkDays, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemSessionOther, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SystemLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemLecturerActionPerformed
        // TODO add your handling code here:
        new SystemLecturer().setVisible(true);
    }//GEN-LAST:event_SystemLecturerActionPerformed

    private void SystemSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemSubjectActionPerformed
        // TODO add your handling code here:
        new SystemSubject().setVisible(true);
    }//GEN-LAST:event_SystemSubjectActionPerformed

    private void SystemTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemTagActionPerformed
        // TODO add your handling code here:
         new SystemTags().setVisible(true);
    }//GEN-LAST:event_SystemTagActionPerformed

    private void SystemLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemLocationActionPerformed
        // TODO add your handling code here:
        new LocationDashboard().setVisible(true);
    }//GEN-LAST:event_SystemLocationActionPerformed

    private void SystemWorkDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemWorkDaysActionPerformed
        // TODO add your handling code here:
        new SystemWorkingDays().setVisible(true);
        
    }//GEN-LAST:event_SystemWorkDaysActionPerformed

    private void SystemTimeTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemTimeTableActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SystemTimeTableActionPerformed

    private void SystemStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemStatisticActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SystemStatisticActionPerformed

    private void SystemStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemStudentActionPerformed
        // TODO add your handling code here:
        new SystemStudent().setVisible(true);
        
    }//GEN-LAST:event_SystemStudentActionPerformed

    private void SystemSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemSessionActionPerformed
        // TODO add your handling code here:
        new SystemSession().setVisible(true);
    }//GEN-LAST:event_SystemSessionActionPerformed

    private void SystemSessionOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemSessionOtherActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_SystemSessionOtherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SystemLecturer;
    private javax.swing.JButton SystemLocation;
    private javax.swing.JButton SystemSession;
    private javax.swing.JButton SystemSessionOther;
    private javax.swing.JButton SystemStatistic;
    private javax.swing.JButton SystemStudent;
    private javax.swing.JButton SystemSubject;
    private javax.swing.JButton SystemTag;
    private javax.swing.JButton SystemTimeTable;
    private javax.swing.JButton SystemWorkDays;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
